name: Laravel Pint

on:
  push:
    branches:
      - main


jobs:
  laravel-pint:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write


    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'
          nova-email: ${{secrets.NOVA_EMAIL}}
          nova-password: ${{secrets.NOVA_PASSWORD}}

      - name: Install Laravel Pint
        run: composer global require laravel/pint

      - name: Run Pint
        run: pint

      - name: Pusth Changes back to the repo
        run: |
          git config user.name "gh-actions"
          git config user.email "gh@laracasts.com"
          git add .
          git commit -m "Laravel Pint" || exit 0
          git push
