name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]


jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write

    services:
      redis:
        image: redis:7.4
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.3


      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.4'
          php-extensions: 'dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite'
          nova-email: ${{secrets.NOVA_EMAIL}}
          nova-password:  ${{secrets.NOVA_PASSWORD}}
          coverage: xdebug




      - name: Install Dependencies
        run: composer install -q --no-interaction

      - name: Prep Application
        run: |
          touch database/database.sqlite
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test --compact --coverage

